#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-

from cmk.graphing.v1 import Title, metrics

UNIT_BYTES = metrics.Unit(metrics.IECNotation('B'))
UNIT_COUNTER = metrics.Unit(metrics.DecimalNotation(''), metrics.StrictPrecision(2))
UNIT_COUNTER_IMPORTED = metrics.Unit(metrics.DecimalNotation('imported'), metrics.StrictPrecision(2))
UNIT_PER_SECOND = metrics.Unit(metrics.DecimalNotation('/s'))
UNIT_TIME = metrics.Unit(metrics.TimeNotation())

metric_Protocols = metrics.Metric(name='Protocols', title=Title("Protocols"), unit=UNIT_BYTES, color=metrics.Color.DARK_PINK,)
metric_ROA_tables = metrics.Metric(name='ROA_tables', title=Title("ROA Tables"), unit=UNIT_BYTES, color=metrics.Color.DARK_PINK,)
metric_Route_attributes = metrics.Metric(name='Route_attributes', title=Title("Route Attributes"), unit=UNIT_BYTES, color=metrics.Color.DARK_BLUE,)
metric_Routing_tables = metrics.Metric(name='Routing_tables', title=Title("Routing Tables"), unit=UNIT_BYTES, color=metrics.Color.GREEN,)
metric_Total = metrics.Metric(name='Total', title=Title("Total"), unit=UNIT_BYTES, color=metrics.Color.ORANGE,)
metric_route_change_stats_Export_updates_accepted = metrics.Metric(name='route_change_stats_Export_updates_accepted', title=Title("Export updates accepted"), unit=UNIT_PER_SECOND, color=metrics.Color.DARK_PINK,)
metric_route_change_stats_Export_updates_filtered = metrics.Metric(name='route_change_stats_Export_updates_filtered', title=Title("Export updates filtered"), unit=UNIT_PER_SECOND, color=metrics.Color.DARK_PURPLE,)
metric_route_change_stats_Export_updates_ignored = metrics.Metric(name='route_change_stats_Export_updates_ignored', title=Title("Export updates ignored"), unit=UNIT_PER_SECOND, color=metrics.Color.PURPLE,)
metric_route_change_stats_Export_updates_received = metrics.Metric(name='route_change_stats_Export_updates_received', title=Title("Export updates received"), unit=UNIT_PER_SECOND, color=metrics.Color.GREEN,)
metric_route_change_stats_Export_updates_rejected = metrics.Metric(name='route_change_stats_Export_updates_rejected', title=Title("Export updates rejected"), unit=UNIT_PER_SECOND, color=metrics.Color.DARK_GRAY,)
metric_route_change_stats_Export_withdraws_accepted = metrics.Metric(name='route_change_stats_Export_withdraws_accepted', title=Title("Export withdraws accepted"), unit=UNIT_PER_SECOND, color=metrics.Color.CYAN,)
metric_route_change_stats_Export_withdraws_filtered = metrics.Metric(name='route_change_stats_Export_withdraws_filtered', title=Title("Export withdraws filtered"), unit=UNIT_PER_SECOND, color=metrics.Color.DARK_BLUE,)
metric_route_change_stats_Export_withdraws_ignored = metrics.Metric(name='route_change_stats_Export_withdraws_ignored', title=Title("Export withdraws ignored"), unit=UNIT_PER_SECOND, color=metrics.Color.DARK_CYAN,)
metric_route_change_stats_Export_withdraws_received = metrics.Metric(name='route_change_stats_Export_withdraws_received', title=Title("Export withdraws received"), unit=UNIT_PER_SECOND, color=metrics.Color.DARK_YELLOW,)
metric_route_change_stats_Export_withdraws_rejected = metrics.Metric(name='route_change_stats_Export_withdraws_rejected', title=Title("Export withdraws rejected"), unit=UNIT_PER_SECOND, color=metrics.Color.LIGHT_GRAY,)
metric_route_change_stats_Import_updates_accepted = metrics.Metric(name='route_change_stats_Import_updates_accepted', title=Title("Import updates accepted"), unit=UNIT_PER_SECOND, color=metrics.Color.DARK_ORANGE,)
metric_route_change_stats_Import_updates_filtered = metrics.Metric(name='route_change_stats_Import_updates_filtered', title=Title("Import updates filtered"), unit=UNIT_PER_SECOND, color=metrics.Color.GREEN,)
metric_route_change_stats_Import_updates_ignored = metrics.Metric(name='route_change_stats_Import_updates_ignored', title=Title("Import updates ignored"), unit=UNIT_PER_SECOND, color=metrics.Color.DARK_GRAY,)
metric_route_change_stats_Import_updates_received = metrics.Metric(name='route_change_stats_Import_updates_received', title=Title("Import updates received"), unit=UNIT_PER_SECOND, color=metrics.Color.DARK_BLUE,)
metric_route_change_stats_Import_updates_rejected = metrics.Metric(name='route_change_stats_Import_updates_rejected', title=Title("Import updates rejected"), unit=UNIT_PER_SECOND, color=metrics.Color.DARK_CYAN,)
metric_route_change_stats_Import_withdraws_accepted = metrics.Metric(name='route_change_stats_Import_withdraws_accepted', title=Title("Import withdraws accepted"), unit=UNIT_PER_SECOND, color=metrics.Color.LIGHT_BROWN,)
metric_route_change_stats_Import_withdraws_filtered = metrics.Metric(name='route_change_stats_Import_withdraws_filtered', title=Title("Import withdraws filtered"), unit=UNIT_PER_SECOND, color=metrics.Color.GRAY,)
metric_route_change_stats_Import_withdraws_ignored = metrics.Metric(name='route_change_stats_Import_withdraws_ignored', title=Title("Import withdraws ignored"), unit=UNIT_PER_SECOND, color=metrics.Color.LIGHT_BROWN,)
metric_route_change_stats_Import_withdraws_received = metrics.Metric(name='route_change_stats_Import_withdraws_received', title=Title("Import withdraws received"), unit=UNIT_PER_SECOND, color=metrics.Color.GREEN,)
metric_route_change_stats_Import_withdraws_rejected = metrics.Metric(name='route_change_stats_Import_withdraws_rejected', title=Title("Import withdraws rejected"), unit=UNIT_PER_SECOND, color=metrics.Color.DARK_BLUE,)
metric_route_stats_exported = metrics.Metric(name='route_stats_exported', title=Title("Prefixes Exported"), unit=UNIT_COUNTER, color=metrics.Color.LIGHT_PINK,)
metric_route_stats_imported = metrics.Metric(name='route_stats_imported', title=Title("Prefixes Imported"), unit=UNIT_COUNTER, color=metrics.Color.DARK_PINK,)
metric_route_stats_preferred = metrics.Metric(name='route_stats_preferred', title=Title("Prefixes Preferred"), unit=UNIT_COUNTER, color=metrics.Color.ORANGE,)
metric_since = metrics.Metric(name='since', title=Title("Since"), unit=UNIT_TIME, color=metrics.Color.DARK_PINK,)
metric_time_since_last_reconfiguration = metrics.Metric(name='time_since_last_reconfiguration', title=Title("Time since last reconfiguration"), unit=UNIT_TIME, color=metrics.Color.DARK_PINK,)
